### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by benardop** [saikatgpae/to-do-list#8]
@saikatgpae , good work on this project so far! 👍 
Just have one issue to point out:
-  How about you check the text inputs entries to prevent the entry of blank string values? 
-  You may also check the font size of your footer text. You may please choose a more visible font size for the text.

**Comment by saikatgpae** [comment]
Thank you for your suggestion 👍 .
Changed the font size of the footer.
Fixed the bug also.
